### PR TITLE
NuGet feed auth support for Azure DevOps, Azure DevOps Server, and third-party NuGet servers

### LINKED ISSUE #1232: Error while generating commit message: Passed `nil` into T.must
**Describe the bug**
Our dependabot is configured to only create PR's on vulnerabilities. Today it found one, but the pipeline fails with this error (it used to work with v1.24 but that one does not exist anymore).

**Categorization**
- [x] This is not a permissions issue (We cannot solve permission issues)

**Repository**
Private :(

**To Reproduce**
Have a project with SixLabors.ImageSharp 3.1.4 in the Nuget. Earliest non-vulnerable is 3.1.5.

**Expected behavior**
Vulnerability is detected (OK), and PR is created (NOK).

**Screenshots**
I'll paste the stacktrace instead of a chain of screenshots:
```
2024-07-23T03:13:36.4688683Z Submitting SixLabors.ImageSharp pull request for creation.
2024-07-23T03:13:36.4710984Z E, [2024-07-23T03:13:36.470518 #7] ERROR -- : Error while generating commit message: Passed `nil` into T.must
2024-07-23T03:13:36.4711494Z E, [2024-07-23T03:13:36.470567 #7] ERROR -- : /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/_types.rb:222:in `must'
2024-07-23T03:13:36.4712000Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.266.0/lib/dependabot/pull_request_creator/message_builder.rb:285:in `pr_name_directory'
2024-07-23T03:13:36.4712475Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024-07-23T03:13:36.4712958Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024-07-23T03:13:36.4713428Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024-07-23T03:13:36.4713917Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.266.0/lib/dependabot/pull_request_creator/message_builder.rb:185:in `solo_pr_name'
2024-07-23T03:13:36.4714380Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024-07-23T03:13:36.4714840Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024-07-23T03:13:36.4715297Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024-07-23T03:13:36.4715773Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.266.0/lib/dependabot/pull_request_creator/message_builder.rb:115:in `pr_name'
2024-07-23T03:13:36.4716235Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024-07-23T03:13:36.4716690Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024-07-23T03:13:36.4717157Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024-07-23T03:13:36.4717638Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.266.0/lib/dependabot/pull_request_creator/message_builder.rb:292:in `commit_subject'
2024-07-23T03:13:36.4718099Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024-07-23T03:13:36.4718693Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024-07-23T03:13:36.4719244Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024-07-23T03:13:36.4719725Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.266.0/lib/dependabot/pull_request_creator/message_builder.rb:159:in `commit_message'
2024-07-23T03:13:36.4720192Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024-07-23T03:13:36.4720643Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024-07-23T03:13:36.4721110Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024-07-23T03:13:36.4721575Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.266.0/lib/dependabot/pull_request_creator.rb:315:in `azure_creator'
2024-07-23T03:13:36.4722027Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024-07-23T03:13:36.4722486Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024-07-23T03:13:36.4722951Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024-07-23T03:13:36.4723407Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.266.0/lib/dependabot/pull_request_creator.rb:241:in `create'
2024-07-23T03:13:36.4728733Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024-07-23T03:13:36.4729726Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024-07-23T03:13:36.4730197Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024-07-23T03:13:36.4730471Z bin/update_script.rb:843:in `block in <main>'
2024-07-23T03:13:36.4730655Z bin/update_script.rb:556:in `each'
2024-07-23T03:13:36.4730848Z bin/update_script.rb:556:in `<main>'
2024-07-23T03:13:36.4731961Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/_types.rb:222:in `must': Passed `nil` into T.must (TypeError)
2024-07-23T03:13:36.4732131Z 
2024-07-23T03:13:36.4732295Z       raise TypeError.new("Passed `nil` into T.must")
2024-07-23T03:13:36.4732458Z             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-23T03:13:36.4732867Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.266.0/lib/dependabot/pull_request_creator/message_builder.rb:285:in `pr_name_directory'
2024-07-23T03:13:36.4733368Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation_2_7.rb:59:in `bind_call'
2024-07-23T03:13:36.4733886Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation_2_7.rb:59:in `block in create_validator_method_fast0'
2024-07-23T03:13:36.4734404Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.266.0/lib/dependabot/pull_request_creator/message_builder.rb:185:in `solo_pr_name'
2024-07-23T03:13:36.4734889Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation_2_7.rb:59:in `bind_call'
2024-07-23T03:13:36.4735501Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation_2_7.rb:59:in `block in create_validator_method_fast0'
2024-07-23T03:13:36.4736081Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.266.0/lib/dependabot/pull_request_creator/message_builder.rb:115:in `pr_name'
2024-07-23T03:13:36.4736563Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation_2_7.rb:59:in `bind_call'
2024-07-23T03:13:36.4737068Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation_2_7.rb:59:in `block in create_validator_method_fast0'
2024-07-23T03:13:36.4737588Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.266.0/lib/dependabot/pull_request_creator/message_builder.rb:292:in `commit_subject'
2024-07-23T03:13:36.4738069Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation_2_7.rb:59:in `bind_call'
2024-07-23T03:13:36.4738590Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation_2_7.rb:59:in `block in create_validator_method_fast0'
2024-07-23T03:13:36.4739105Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.266.0/lib/dependabot/pull_request_creator/message_builder.rb:166:in `rescue in commit_message'
2024-07-23T03:13:36.4739609Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.266.0/lib/dependabot/pull_request_creator/message_builder.rb:158:in `commit_message'
2024-07-23T03:13:36.4740082Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024-07-23T03:13:36.4740560Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024-07-23T03:13:36.4741046Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024-07-23T03:13:36.4741772Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.266.0/lib/dependabot/pull_request_creator.rb:315:in `azure_creator'
2024-07-23T03:13:36.4742253Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024-07-23T03:13:36.4742725Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024-07-23T03:13:36.4743208Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024-07-23T03:13:36.4743675Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.266.0/lib/dependabot/pull_request_creator.rb:241:in `create'
2024-07-23T03:13:36.4744132Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024-07-23T03:13:36.4744603Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024-07-23T03:13:36.4745073Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024-07-23T03:13:36.4745359Z 	from bin/update_script.rb:843:in `block in <main>'
2024-07-23T03:13:36.4745634Z 	from bin/update_script.rb:556:in `each'
2024-07-23T03:13:36.4745832Z 	from bin/update_script.rb:556:in `<main>'
2024-07-23T03:13:36.4746232Z /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/_types.rb:222:in `must': Passed `nil` into T.must (TypeError)
2024-07-23T03:13:36.4746439Z 
2024-07-23T03:13:36.4746601Z       raise TypeError.new("Passed `nil` into T.must")
2024-07-23T03:13:36.4746771Z             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-23T03:13:36.4747164Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.266.0/lib/dependabot/pull_request_creator/message_builder.rb:285:in `pr_name_directory'
2024-07-23T03:13:36.4747639Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024-07-23T03:13:36.4748101Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024-07-23T03:13:36.4748589Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024-07-23T03:13:36.4749077Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.266.0/lib/dependabot/pull_request_creator/message_builder.rb:185:in `solo_pr_name'
2024-07-23T03:13:36.4749550Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024-07-23T03:13:36.4750021Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024-07-23T03:13:36.4750497Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024-07-23T03:13:36.4750983Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.266.0/lib/dependabot/pull_request_creator/message_builder.rb:115:in `pr_name'
2024-07-23T03:13:36.4751454Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024-07-23T03:13:36.4751929Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024-07-23T03:13:36.4752407Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024-07-23T03:13:36.4752896Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.266.0/lib/dependabot/pull_request_creator/message_builder.rb:292:in `commit_subject'
2024-07-23T03:13:36.4753363Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024-07-23T03:13:36.4753839Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024-07-23T03:13:36.4754316Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024-07-23T03:13:36.4754792Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.266.0/lib/dependabot/pull_request_creator/message_builder.rb:159:in `commit_message'
2024-07-23T03:13:36.4755267Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024-07-23T03:13:36.4755740Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024-07-23T03:13:36.4756320Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024-07-23T03:13:36.4756834Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.266.0/lib/dependabot/pull_request_creator.rb:315:in `azure_creator'
2024-07-23T03:13:36.4757300Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024-07-23T03:13:36.4757767Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024-07-23T03:13:36.4758239Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024-07-23T03:13:36.4758692Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-common-0.266.0/lib/dependabot/pull_request_creator.rb:241:in `create'
2024-07-23T03:13:36.4759142Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024-07-23T03:13:36.4759614Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024-07-23T03:13:36.4760087Z 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11485/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024-07-23T03:13:36.4760364Z 	from bin/update_script.rb:843:in `block in <main>'
2024-07-23T03:13:36.4760565Z 	from bin/update_script.rb:556:in `each'
2024-07-23T03:13:36.4760758Z 	from bin/update_script.rb:556:in `<main>'
2024-07-23T03:13:37.0176721Z ##[error]The process '/usr/bin/docker' failed with exit code 1
2024-07-23T03:13:37.0208637Z ##[section]Finishing: Run Dependabot
```

Pool: Azure Pipelines
Image: ubuntu-latest
Agent: Hosted Agent

Version      : 1.30.776
Unable to find image 'ghcr.io/tinglesoftware/dependabot-updater-nuget:1.30' locally
1.30: Pulling from tinglesoftware/dependabot-updater-nuget

**Additional context**
Dependabot 1.30 still complains about 401 errors on private feeds (telerik) but the vulnerable package is a public one. And I can't test with the 1.24 image anymore :(

### LINKED ISSUE #1234: Fix code scanning alert - Incomplete URL substring sanitization
Tracking issue for:
- [ ] https://github.com/tinglesoftware/dependabot-azure-devops/security/code-scanning/23

### PR DESCRIPTION
**Pull request by rhyskoedijk**
### What are you trying to accomplish?
Fixes #1232
Fixes #1234

After debugging through #1232, I've realised that `ArtifactsCredentialProvider` should not restrict itself to only "dev.azure.com" feeds; instead it should pass-through credentials to **all** NuGet feeds.

It should be possible to configure NuGet auth for Azure DevOps, Azure DevOps Server, and any third-party NuGet package servers using basic auth. For example, see https://github.com/tinglesoftware/dependabot-azure-devops/issues/1232#issuecomment-2247616424.

### Changes
- Updated [README.MD](https://github.com/tinglesoftware/dependabot-azure-devops/pull/1241/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) with example of how to auth with a third-party NuGet server requiring basic auth.
- Remove host name whitelisting in `ArtifactsCredentialProvider` 
- `Job` no longer sets default credentials for "pkgs.dev.azure.com", use `DEPENDABOT_EXTRA_CREDENTIALS` instead.
- Extension task now replaces placeholder environment variable names for "registries.username" in dependabot.yml.

### CODE REVIEW

**Comment by rhyskoedijk** [comment]
I'm not sure how to test this passes the rule, but based on the [examples](https://codeql.github.com/codeql-query-help/ruby/rb-incomplete-url-substring-sanitization/#example), it _should_ pass

File: updater/lib/tinglesoftware/azure/artifacts_credential_provider.rb [hunk 1]
```diff
@@ -16,22 +18,26 @@ module Azure
     module ArtifactsCredentialProvider
       def self.install_if_nuget_feeds_are_configured
         credentials = JSON.parse(ENV.fetch("DEPENDABOT_EXTRA_CREDENTIALS", "[]"))
-        private_ado_nuget_feeds = credentials.select do |cred|
-          cred["type"] == "nuget_feed" && cred["url"].include?("dev.azure.com")
+        private_nuget_feeds = credentials.select do |cred|
+          cred["type"] == "nuget_feed"
         end
```
Comment (mburumaxwell) [inline updater/lib/tinglesoftware/azure/artifacts_credential_provider.rb:23]: We should exclude non-private feeds here such as public feeds for daily builds. Checking for presence or username/token should be enough.

**Review by mburumaxwell — CHANGES_REQUESTED** [review]

File: extension/task/task.json
[the remark this answers is not in the document]
Comment (rhyskoedijk) [reply extension/task/task.json:1]: ah, that makes sense. I've reverted the change

File: updater/lib/tinglesoftware/azure/artifacts_credential_provider.rb (hunk 1 above)
Comment (rhyskoedijk) [reply updater/lib/tinglesoftware/azure/artifacts_credential_provider.rb]: good point, forgot about public feeds

**Review by mburumaxwell — APPROVED** [review]

**Comment by mburumaxwell** [comment]
Fixes #1243?
